repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: debug-statements
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.11
      - id: black-jupyter
        language_version: python3.11
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=127, --extend-ignore=E203] # black and flake8 disagree on E203
  - repo: local
    hooks:
      - id: testing
        name: testing
        entry: pytest
        language: system
        files: ^test/ # ^ means 'start with test/'
        always_run: true # run on all files, not just those staged
